# 姓名到邮箱映射表
# 来源：0709教育部经费余额梳理-发泽琛(1)-已填充邮箱.xlsx 的"邮箱"sheet
EMAIL_MAP = {
    "丰子淇": "fengziqi@dlut.edu.cn",
    "任欣欣": "renxinxin@dlut.edu.cn",
    "何尊": "hezun@dlut.edu.cn",
    "冯卓": "zhfeng@dlut.edu.cn",
    "刁秀华": "diaoxiuhua@dlut.edu.cn",
    "刘嘉莹": "jiayingliu@dlut.edu.cn",
    "刘孟洋": "mengyangliu@126.com",
    "刘晏如": "yanru.liu0628@foxmail.com",
    "吴启竞": "alicewu@dlut.edu.cn",
    "周惠巍": "zhou_huiwei@163.com",
    "商华": "shanghua@dlut.edu.cn",
    "姜华": "jianghua@dlut.edu.cn",
    "孙晓华": "sxh_dut@sina.com",
    "孙迪": "sundi@dlut.edu.cn",
    "宋明亮": "ammiyas@dlut.edu.cn",
    "宋金波": "songjinbo@dlut.edu.cn",
    "张丽": "zlzzb@dlut.edu.cn",
    "张卫": "zhwei@dlut.edu.cn",
    "张君": "JunZhang@dlut.edu.cn",
    "张弘驰": "zhanghc@dlut.edu.cn",
    "张超": "zhangchao@dlut.edu.cn",
    "徐博": "xubo@dlut.edu.cn",
    "朱焱": "zhuy@dlut.edu.cn",
    "李东遥": "lidongyao@dlut.edu.cn",
    "李冲": "culture@dlut.edu.cn",
    "李天石": "litianshi@dlut.edu.cn",
    "李彤": "litong@dlut.edu.cn",
    "李树文": "lishuwen@dlut.edu.cn",
    "李琳": "lilin@dlut.edu.cn",
    "李鹏": "lipeng@dlut.edu.cn",
    "杨慧民": "yhm7426@dlut.edu.cn",
    "杨木": "yangmu@dlut.edu.cn",
    "杨琳": "yanglin@dlut.edu.cn",
    "林杰": "linjie@dlut.edu.cn",
    "洪晓楠": "hongxn@dlut.edu.cn",
    "潘雄锋": "xiongfengpan@163.com",
    "王一": "martin8737@dlut.edu.cn",
    "王俊杰": "wangjunjie@dlut.edu.cn",
    "王欢明": "whm715@dlut.edu.cn",
    "王良": "wangliang9170@dlut.edu.cn",
    "石丹": "shidan56@dlut.edu.cn",
    "董丽": "donglila@dlut.edu.cn",
    "贾依帛": "jiayibo@dlut.edu.cn",
    "贾枭": "jiax@dlut.edu.cn",
    "贾迪": "jiadi0914@dlut.edu.cn",
    "赵蒙": "zhaomeng@dlut.edu.cn",
    "赵雪": "xuerzhao@126.com",
    "邵慧峰": "shaohuifeng@dlut.edu.cn",
    "郭玲玲": "guolingling@dlut.edu.cn",
    "陈悦": "chenyue@dlut.edu.cn",
    "陈肖东": "xiaodong@dlut.edu.cn",
    "陈雪龙": "chenxl_dg@dlut.edu.cn",
    "高景鑫": "gjxin29@dlut.edu.cn",
}

"""
共 53 人
"""